kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kms
spec:
  to:
    kind: Service
    name: kms
  port:
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: kms
  labels:
    app: kms
spec:
  ports:
    - port: 8085
      name: http
  selector:
    app: kms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kms
  labels:
    app: kms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kms
  template:
    metadata:
      labels:
        app: kms
    spec:
      containers:
        - name: app
          image: quay.io/jonkey/biz-platform-kms
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: myapps.storage.root
              value: /storage
            - name: spring.datasource.url
              value: jdbc:mysql://mysql:3306/mydb?characterEncoding=UTF-8&serverTimezone=GMT
            - name: spring.datasource.username
              value: "mysql"
            - name: spring.datasource.password
              value: "mysql"
            - name: spring.redis.host
              value: redis
            - name: spring.cloud.consul.host
              value: consul-server
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
              scheme: HTTP
          volumeMounts:
          - name: storage
            mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
