kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: adminer
spec:
  to:
    kind: Service
    name: adminer
  port:
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: adminer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: app
          image: quay.io/jonkey/adminer:4.8.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          