apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx_conf: |-
    #user  nobody;
    worker_processes  1;
    events {
        worker_connections  1024;
    }
    http {
        include       mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;
        gzip  on;
        server {
            listen       8080;
            server_name  localhost;
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   html;
            }
            location /signon {
                proxy_pass http://gateway:8080/signon;
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET,POST,DELETE,PUT';
                add_header 'Access-Control-Allow-Header' 'Content-Type,*';
            }
            location /obpm {
                proxy_pass http://gateway:8080/obpm;
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET,POST,DELETE,PUT';
                add_header 'Access-Control-Allow-Header' 'Content-Type,*';
            }
            location /obpm-kms {
                proxy_pass http://gateway:8080/kms;
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET,POST,DELETE,PUT';
                add_header 'Access-Control-Allow-Header' 'Content-Type,*';
            }
            location /email {
                proxy_pass http://gateway:8080/email;
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET,POST,DELETE,PUT';
                add_header 'Access-Control-Allow-Header' 'Content-Type,*';
            }
            location /message {
                proxy_pass http://gateway:8080/message;
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET,POST,DELETE,PUT';
                add_header 'Access-Control-Allow-Header' 'Content-Type,*';
            }
            location /obpm-designer {
                proxy_pass http://designer:8082/designer;
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET,POST,DELETE,PUT';
                add_header 'Access-Control-Allow-Header' 'Content-Type,*';
            }
        }
    }
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: static
spec:
  to:
    kind: Service
    name: static
  port:
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: static
  labels:
    app: static
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: static
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static
  labels:
    app: static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
        - name: app
          image: quay.io/jonkey/biz-platform-static
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "[ -f /run/nginx.pid ] && ps -A | grep nginx"
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /index.html
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: nginx-conf
            subPath: nginx.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx_conf
              path: nginx.conf
